{% set name = "pywhat" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pywhat-{{ version }}.tar.gz
  sha256: bf0fb5637441566c23868a1ed349209d673dfa477cc11bb5f5bc7390d04c9ed1

build:
  number: 0
  noarch: python
  entry_points:
    - pywhat = pywhat.what:main
    - what = pywhat.what:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<4.0
  run:
    - click >=7.1.2,<8.0.0
    - langdetect >=1.0.8,<2.0.0
    - name_that_hash >=1.7.0,<2.0.0
    - python >=3.6,<4.0
    - rich >=9.9,<11.0

test:
  imports:
    - pywhat
  commands:
    - pip check
    - pywhat --help
    - what --help
  requires:
    - pip

about:
  home: https://github.com/bee-san/pyWhat
  summary: What is that thing?
  license: GPL-3.0-only
  license_file: LICENSE
  description: |
    PyWhat's job is to identify what something is. Whether it be a file or text!
     Or even the hex of a file! What about text within files? We have that too!
     what is recursive, it will identify everything in text and more!

extra:
  recipe-maintainers:
    - thewchan
