{% set name = "pywhat" %}
{% set version = "5.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pywhat-{{ version }}.tar.gz
  sha256: 8a6f2b3060f5ce9808802b9ca3eaf91e19c932e4eaa03a4c2e5255d0baad85c4

build:
  number: 1
  noarch: python
  entry_points:
    - pywhat = pywhat.what:main
    - what = pywhat.what:main
  script:
    # Removing pyproject.toml here due to pip bug
    - {{ PYTHON }} -c "__import__('os').unlink('pyproject.toml')"
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python {{ python_min }}
  run:
    - click >=7.1.2,<8.0.0
    - orjson >=3.6.1
    - python >={{ python_min }},<4.0
    - rich >=9.9,<11.0

test:
  imports:
    - pywhat
  commands:
    - pip check
    - pywhat --help
    - what --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bee-san/pyWhat
  summary: What is that thing?
  license: GPL-3.0-only
  license_file: LICENSE
  description: |
    PyWhat's job is to identify what something is. Whether it be a file or text!
     Or even the hex of a file! What about text within files? We have that too!
     what is recursive, it will identify everything in text and more!

extra:
  recipe-maintainers:
    - thewchan
